# Generated by Django 5.0.3 on 2024-04-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='on_of_items',
            new_name='no_of_items',
        ),
    ]
