# Generated by Django 5.0.3 on 2024-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_on_of_items_order_no_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
