# Generated by Django 5.0.3 on 2024-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='desc',
            field=models.TextField(),
        ),
    ]
